# Generated by Django 5.2.5 on 2025-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.TextField(help_text='Comma-separated list of keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resumes/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
    ]
